version: "3.8"

services:
  frontend:
    restart: always
    depends_on:
      - api
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
      args:
        - VITE_API_BASE_URL=http://localhost:5555/
    ports:
      - "80:80"
  api:
    restart: always
    depends_on:
      - db
    build:
      context: ./api
      dockerfile: ./Dockerfile
    ports:
      - "5555:5000"
  db:
    restart: always 
    build:
      context: ./db
      dockerfile: Dockerfile