version: "3.8"

services:
  frontend:
    restart: always
    depends_on:
      - api
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
  api:
    restart: always
    depends_on:
      - db
    build:
      context: ./api
      dockerfile: ./Dockerfile
    ports:
      - "5000:5000"
  db:
    restart: always 
    build:
      context: ./db
      dockerfile: Dockerfile
    ports:
      - "5432:5432"