apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
 name: dev
 namespace: time-capsule
rules:
- apiGroups:
  - ""
  resources: ["*"]
  verbs:
    - get
    - list
    - watch
    - create
    - update
    - patch
    - delete