apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: time-capsule
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
        policy: frontend
    spec:
      containers:
      - name: frontend
        image: segerritsen/time-capsule-frontend:1.0
        imagePullPolicy: Always
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
        - name: API_BASE_URL
          valueFrom:
            configMapKeyRef:
              name: frontend-config
              key: api-base-url
        ports:
        - containerPort: 80