apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: time-capsule
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: segerritsen/time-capsule-api:1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 5000