apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: time-capsule
spec:
  type: LoadBalancer
  selector:
    app: frontend
  externalIPs:
   - 192.168.49.2
  ports:
   - port: 80
     targetPort: 80