apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: time-capsule-manage-secrets
  namespace: time-capsule
subjects:
- kind: User
  name: cindy
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: time-capsule-secret-manager
  apiGroup: rbac.authorization.k8s.io
