apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: time-capsule
  name: time-capsule-storage-admin
rules:
- apiGroups: [""]
  resources: ["persistentvolumes", "persistentvolumeclaims", "storageclasses"]
  verbs: ["get", "list", "watch", "create", "update", "delete"]

