apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: storage-admin
  namespace: time-capsule
subjects:
- kind: User
  name: serge
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: time-capsule-storage-admin
  apiGroup: rbac.authorization.k8s.io
