apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: time-capsule
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
        policy: api
    spec:
      containers:
      - name: api
        image: europe-west4-docker.pkg.dev/time-capsule-412314/time-capsule/api:1.0
        imagePullPolicy: Always
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: db-host
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: db-port
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: db-name
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: db-username
        - name: DB_PASSWD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: db-password
        ports:
        - containerPort: 5000